export const servicePages = {
  'resume-builder': {
    title: ['A RESUME', 'THAT MAKES', 'YOUR WORK', 'CLEAR.'],
    eyebrow: 'CAREER SERVICE / 01',
    summary: 'A thoughtful resume brings your experience into focus and helps a reader understand what you could contribute next.',
    introTitle: 'A strong resume is a clear conversation.',
    intro: 'We help you shape a precise, readable account of your skills, experience and direction. The details stay yours; the structure helps them come through.',
    focus: 'Build a story that fits the next step.',
    photo: 'photo-1454165804606-c3d57bc86b40',
    photoAlt: 'Professional reviewing documents at a desk',
    secondPhoto: 'photo-1516321318423-f06f85e504b3',
    secondAlt: 'Professional working through career documents',
    theme: 'paper', layout: 'editorial', visual: 'document',
    points: [
      ['01', 'Start with substance', 'Identify relevant responsibilities, outcomes and skills without inflating the facts.'],
      ['02', 'Bring the story forward', 'Organize content so a hiring team can scan your strengths and experience.'],
      ['03', 'Tailor with care', 'Adjust emphasis and language for the direction you want to pursue.'],
    ],
    stages: ['Understand your goals', 'Shape the experience', 'Review and refine'],
    cta: 'Bring your experience into focus.',
    related: [['Profile Marketing', '/services/profile-marketing'], ['Interview Preparation', '/services/interview-preparation']],
  },
  'profile-marketing': {
    title: ['BE CLEAR.', 'BE FOUND.', 'BE READY', 'TO CONNECT.'],
    eyebrow: 'CAREER SERVICE / 02',
    summary: 'Make your professional profile a consistent, confident introduction to the work you do and the work you want.',
    introTitle: 'Your profile is part of your story.',
    intro: 'A focused professional presence makes it easier for people to understand your strengths. We help align your profile, resume and career direction.',
    focus: 'Position your experience with intention.',
    photo: 'photo-1521737711867-e3b97375f902',
    photoAlt: 'Professionals discussing work together in an office',
    secondPhoto: 'photo-1522071820081-009f0129c71c',
    secondAlt: 'Colleagues collaborating around a table',
    theme: 'night', layout: 'terminal', visual: 'profile',
    points: [
      ['01', 'LinkedIn optimization', 'Make your experience and professional focus easier to scan.'],
      ['02', 'Professional positioning', 'Create a consistent narrative across your profile and resume.'],
      ['03', 'Keyword strategy', 'Use role-relevant language that accurately describes your capabilities.'],
      ['04', 'Profile visibility', 'Strengthen the signals that help the right audience find your work.'],
      ['05', 'Resume distribution', 'Prepare a clear profile package for relevant conversations.'],
    ],
    stages: ['Clarify your direction', 'Align your profile', 'Prepare to connect'],
    cta: 'Make your next introduction count.',
    related: [['Resume Builder', '/services/resume-builder'], ['Career Support', '/services/career-support']],
  },
  'technical-support': {
    title: ['KNOW THE', 'WORK.', 'EXPLAIN', 'THE WHY.'],
    eyebrow: 'CAREER SERVICE / 03',
    summary: 'Turn what you know into clear, role-focused explanations through technical practice and project conversations.',
    introTitle: 'Understanding is strongest when you can explain it.',
    intro: 'We help candidates revisit relevant technical concepts, practice talking through their approach and prepare for role-specific discussions.',
    focus: 'Practice the skills the role asks you to demonstrate.',
    photo: 'photo-1551836022-d5d88e9218df',
    photoAlt: 'Colleagues discussing a technical project',
    secondPhoto: 'photo-1581091226825-a6a2a5aee158',
    secondAlt: 'Engineer working with technology in a lab setting',
    theme: 'blue', layout: 'cinematic', visual: 'support',
    points: [
      ['01', 'Technical preparation', 'Review role-relevant tools, concepts and ways of thinking.'],
      ['02', 'Mock interviews', 'Practice communicating decisions in a realistic conversation.'],
      ['03', 'Project explanation', 'Describe your contribution, tradeoffs and learning clearly.'],
      ['04', 'Role-specific preparation', 'Focus practice on the responsibilities and requirements in view.'],
    ],
    stages: ['Review the role', 'Practice the thinking', 'Explain your approach'],
    cta: 'Prepare to show how you think.',
    related: [['Interview Preparation', '/services/interview-preparation'], ['IT Staffing', '/it#it-staffing']],
  },
  'interview-preparation': {
    title: ['PRACTICE', 'WITH PURPOSE.', 'MEET THE', 'MOMENT.'],
    eyebrow: 'CAREER SERVICE / 04',
    summary: 'Build calm, clarity and confidence through preparation that feels relevant to the conversations ahead.',
    introTitle: 'Good interviews are conversations, not performances.',
    intro: 'Prepare concise examples, thoughtful questions and a clear way to explain your experience. Practice gives you room to find your own voice.',
    focus: 'Make your experience easy to talk about.',
    photo: 'photo-1552664730-d307ca884978',
    photoAlt: 'Team members in a professional discussion',
    secondPhoto: 'photo-1524758631624-e2822e304c36',
    secondAlt: 'Quiet contemporary space for interview preparation',
    theme: 'ochre', layout: 'poster', visual: 'conversation',
    points: [
      ['01', 'Build your examples', 'Choose specific moments that show how you solve problems and work with others.'],
      ['02', 'Practice the conversation', 'Rehearse answers and questions in a supportive, realistic setting.'],
      ['03', 'Explain your value', 'Connect your experience to the role without losing your natural voice.'],
    ],
    stages: ['Reflect on your work', 'Rehearse with feedback', 'Arrive prepared'],
    cta: 'Go into the conversation prepared.',
    related: [['Technical Support', '/services/technical-support'], ['Resume Builder', '/services/resume-builder']],
  },
  'career-support': {
    title: ['YOUR NEXT', 'MOVE CAN', 'START WITH', 'A PLAN.'],
    eyebrow: 'CAREER SERVICE / 05',
    summary: 'Thoughtful guidance helps turn a broad ambition into a practical next step, at your pace and in your direction.',
    introTitle: 'A career path is built one useful step at a time.',
    intro: 'Explore your goals, make your professional story clearer and prepare for meaningful conversations about what comes next.',
    focus: 'Move forward with a clearer sense of direction.',
    photo: 'photo-1522071820081-009f0129c71c',
    photoAlt: 'Colleagues working together in a bright workplace',
    secondPhoto: 'photo-1524758631624-e2822e304c36',
    secondAlt: 'Open workplace for a thoughtful career conversation',
    theme: 'sage', layout: 'editorial', visual: 'pathway',
    points: [
      ['01', 'Profile evaluation', 'Take stock of your experience, strengths and current direction.'],
      ['02', 'Resume enhancement', 'Present your story in a way that fits the next opportunity.'],
      ['03', 'Interview support', 'Prepare for conversations with practical role-specific practice.'],
      ['04', 'Opportunity matching', 'Explore relevant possibilities with realistic expectations.'],
    ],
    stages: ['Listen and understand', 'Build and prepare', 'Connect and continue'],
    cta: 'Start with the next step that matters to you.',
    related: [['Resume Builder', '/services/resume-builder'], ['Non-IT Careers', '/non-it']],
  },
}

export const industryPages = {
  'ai-machine-learning': {
    title: ['INTELLIGENCE', 'MEETS', 'HUMAN', 'POTENTIAL.'], eyebrow: 'INDUSTRY / AI & MACHINE LEARNING',
    summary: 'Support the people building, training and operating intelligent systems, from applied machine learning to generative AI.',
    introTitle: 'Build AI that belongs in the real world.', intro: 'AI and machine learning roles span research, engineering, data and reliable deployment. Strong teams bring together technical depth and practical judgment.',
    focus: 'From experimentation to responsible application.', photo: 'photo-1677442136019-21780ecad995', photoAlt: 'Abstract visualization representing machine intelligence', secondPhoto: 'photo-1620712943543-bcc4688e7485', secondAlt: 'Colorful abstract technology visualization', theme: 'night', layout: 'terminal', visual: 'network',
    points: [['01', 'AI engineering', 'Design and integrate AI capabilities into useful products and systems.'], ['02', 'Machine learning', 'Develop and evaluate models for applied problems.'], ['03', 'Generative AI & NLP', 'Work with language models, natural language processing and content systems.'], ['04', 'Computer vision & MLOps', 'Build visual understanding and dependable model operations.']],
    stages: ['Frame the problem', 'Build and evaluate', 'Deploy responsibly'], cta: 'Explore the work behind intelligent systems.', related: [['Data & Analytics', '/industries/data-analytics'], ['Software Development', '/industries/software-development']],
  },
  'data-analytics': {
    title: ['TURN DATA', 'INTO', 'BETTER', 'DECISIONS.'], eyebrow: 'INDUSTRY / DATA & ANALYTICS',
    summary: 'Connect people who make information useful with teams that need clarity, reliable systems and better decisions.',
    introTitle: 'Good analysis makes the signal visible.', intro: 'Data work connects collection, quality, modeling and communication. Each role has a different view of the same question: what can this information help us understand?',
    focus: 'From source data to a story people can use.', photo: 'photo-1551288049-bebda4e38f71', photoAlt: 'Business analytics display with charts and information', secondPhoto: 'photo-1460925895917-afdab827c52f', secondAlt: 'Finance and analytics dashboards on a screen', theme: 'paper', layout: 'poster', visual: 'analytics',
    points: [['01', 'Data analyst', 'Explore information, surface patterns and communicate findings.'], ['02', 'Data scientist', 'Use statistical and computational methods to investigate complex questions.'], ['03', 'Data engineer', 'Build dependable pipelines and data foundations.'], ['04', 'BI developer', 'Shape accessible reporting and business intelligence tools.']],
    stages: ['Collect with care', 'Interpret the pattern', 'Communicate the insight'], cta: 'Put information to work.', related: [['AI & Machine Learning', '/industries/ai-machine-learning'], ['Business & Finance', '/industries/business-finance']],
  },
  'software-development': {
    title: ['MAKE THE', 'DIGITAL', 'THINGS', 'WE NEED.'], eyebrow: 'INDUSTRY / SOFTWARE DEVELOPMENT',
    summary: 'Support software professionals who design, build and maintain the digital products people rely on every day.',
    introTitle: 'Software is a craft shaped by collaboration.', intro: 'Product engineering brings together thoughtful design, maintainable code, testing and clear communication across a team.',
    focus: 'Create reliable products through considered engineering.', photo: 'photo-1498050108023-c5249f4df085', photoAlt: 'Developer working at a computer in a bright workspace', secondPhoto: 'photo-1519389950473-47ba0277781c', secondAlt: 'Technology team collaborating on a project', theme: 'blue', layout: 'editorial', visual: 'code',
    points: [['01', 'Frontend engineering', 'Build accessible, responsive product experiences.'], ['02', 'Backend engineering', 'Design services, APIs and data-driven application logic.'], ['03', 'Full-stack development', 'Connect the user experience with dependable server-side systems.'], ['04', 'Quality engineering', 'Improve reliability through thoughtful testing and review.']],
    stages: ['Understand the user', 'Design and build', 'Test and improve'], cta: 'Find your place in the product team.', related: [['QA & Testing', '/industries/qa-testing'], ['Cloud & DevOps', '/industries/cloud-devops']],
  },
  'cloud-devops': {
    title: ['BUILD.', 'DEPLOY.', 'SCALE WITH', 'CONFIDENCE.'], eyebrow: 'INDUSTRY / CLOUD & DEVOPS',
    summary: 'Connect cloud and delivery professionals who help teams operate resilient systems and release software with confidence.',
    introTitle: 'Great infrastructure gives teams room to move.', intro: 'Cloud, platform and DevOps work spans architecture, automation, observability and operational practice. The goal is dependable delivery, not complexity for its own sake.',
    focus: 'Reliable foundations for changing workloads.', photo: 'photo-1451187580459-43490279c0fa', photoAlt: 'View of Earth representing cloud infrastructure', secondPhoto: 'photo-1518770660439-4636190af475', secondAlt: 'Computer hardware and infrastructure components', theme: 'sky', layout: 'cinematic', visual: 'cloud',
    points: [['01', 'Cloud engineering', 'Design and operate solutions across AWS, Azure and Google Cloud.'], ['02', 'DevOps & platform', 'Automate delivery, improve developer workflows and maintain platforms.'], ['03', 'Containers & orchestration', 'Work with Docker, Kubernetes and modern deployment patterns.'], ['04', 'CI/CD & reliability', 'Support repeatable releases, monitoring and service resilience.']],
    stages: ['Design the platform', 'Automate delivery', 'Observe and improve'], cta: 'Build the systems behind the work.', related: [['IT Infrastructure', '/industries/it-infrastructure'], ['Cybersecurity', '/industries/cybersecurity']],
  },
  cybersecurity: {
    title: ['SECURE', 'WHAT', 'MATTERS.', 'EVERY DAY.'], eyebrow: 'INDUSTRY / CYBERSECURITY',
    summary: 'Support security teams protecting services, infrastructure, information and the people who depend on them.',
    introTitle: 'Security is a team practice.', intro: 'Modern security connects monitoring, engineering, governance and risk. Thoughtful professionals help organizations prepare, detect and respond with care.',
    focus: 'Protect systems without losing sight of people.', photo: 'photo-1563013544-824ae1b704d3', photoAlt: 'Abstract security interface on a computer screen', secondPhoto: 'photo-1550751827-4bd374c3f58b', secondAlt: 'Secure network visualization in a technology environment', theme: 'night', layout: 'terminal', visual: 'shield',
    points: [['01', 'Security operations', 'Monitor systems, investigate signals and coordinate response.'], ['02', 'Cloud & network security', 'Help protect the infrastructure and connections organizations rely on.'], ['03', 'Application security', 'Build security into software design, development and review.'], ['04', 'Risk & compliance', 'Support thoughtful controls, governance and risk management.']],
    stages: ['Understand exposure', 'Strengthen controls', 'Monitor and respond'], cta: 'Build trust into the systems people use.', related: [['Cloud & DevOps', '/industries/cloud-devops'], ['IT Infrastructure', '/industries/it-infrastructure']],
  },
  'it-infrastructure': {
    title: ['KEEP THE', 'FOUNDATION', 'MOVING.', 'FORWARD.'], eyebrow: 'INDUSTRY / IT INFRASTRUCTURE',
    summary: 'Infrastructure professionals make the systems, networks and workplace technology behind modern organizations dependable.',
    introTitle: 'The best foundations make everything else possible.', intro: 'Infrastructure roles connect devices, identity, networks, systems and cloud platforms. Careful operations create room for people to do their work.',
    focus: 'Connect, maintain and improve essential systems.', photo: 'photo-1518770660439-4636190af475', photoAlt: 'Close view of computing hardware', secondPhoto: 'photo-1558494949-ef010cbdcc31', secondAlt: 'Rows of network servers in a data center', theme: 'navy', layout: 'editorial', visual: 'infrastructure',
    points: [['01', 'Systems administration', 'Maintain operating systems, services and endpoint environments.'], ['02', 'Network engineering', 'Support connectivity, routing and resilient network operations.'], ['03', 'Identity & access', 'Manage access practices and identity systems.'], ['04', 'IT support', 'Help users solve workplace technology issues with care and clarity.']],
    stages: ['Map the environment', 'Keep services healthy', 'Improve the foundation'], cta: 'Support the systems people count on.', related: [['Cybersecurity', '/industries/cybersecurity'], ['Cloud & DevOps', '/industries/cloud-devops']],
  },
  'qa-testing': {
    title: ['MAKE QUALITY', 'PART OF', 'THE BUILD.', 'FROM DAY ONE.'], eyebrow: 'INDUSTRY / QA & TESTING',
    summary: 'Quality professionals help teams find issues early, protect customer experience and build confidence in every release.',
    introTitle: 'Quality is built through curiosity and care.', intro: 'Testing combines analytical thinking, product understanding and collaboration. The right approach helps a team learn quickly and release with greater confidence.',
    focus: 'Explore what could go wrong before it matters.', photo: 'photo-1516321318423-f06f85e504b3', photoAlt: 'Professional working with a laptop during testing', secondPhoto: 'photo-1551434678-e076c223a692', secondAlt: 'Team working through software development together', theme: 'paper', layout: 'poster', visual: 'qa',
    points: [['01', 'Functional testing', 'Verify how a product behaves against its intended use.'], ['02', 'Test automation', 'Create repeatable checks for reliable development workflows.'], ['03', 'API & performance', 'Examine service behavior, integration and responsiveness.'], ['04', 'Quality assurance', 'Partner with product and engineering teams to improve the whole process.']],
    stages: ['Understand expected behavior', 'Explore edge cases', 'Share useful findings'], cta: 'Help teams ship with confidence.', related: [['Software Development', '/industries/software-development'], ['Cloud & DevOps', '/industries/cloud-devops']],
  },
  'business-finance': {
    title: ['CLARITY FOR', 'THE BUSINESS.', 'CARE WITH', 'THE DETAILS.'], eyebrow: 'INDUSTRY / BUSINESS & FINANCE',
    summary: 'Support finance and business professionals who bring rigor, coordination and perspective to everyday decisions.',
    introTitle: 'Good decisions start with trusted work.', intro: 'Finance and business operations connect analysis, accuracy, communication and sound judgment. These teams help an organization understand its position and act thoughtfully.',
    focus: 'Bring structure and insight to complex decisions.', photo: 'photo-1460925895917-afdab827c52f', photoAlt: 'Business analytics dashboard on a computer display', secondPhoto: 'photo-1454165804606-c3d57bc86b40', secondAlt: 'Professional reviewing financial paperwork', theme: 'sage', layout: 'editorial', visual: 'finance',
    points: [['01', 'Accounting', 'Maintain accurate financial records and support reporting.'], ['02', 'Financial analysis', 'Translate numbers into context for planning and decisions.'], ['03', 'Business operations', 'Coordinate the processes and information teams need to work well.'], ['04', 'Administration', 'Bring reliable organization to daily business activity.']],
    stages: ['Understand the context', 'Work with precision', 'Communicate clearly'], cta: 'Bring your perspective to the work.', related: [['Data & Analytics', '/industries/data-analytics'], ['Non-IT Careers', '/non-it']],
  },
  healthcare: {
    title: ['CARE THAT', 'CONNECTS', 'PEOPLE TO', 'BETTER DAYS.'], eyebrow: 'INDUSTRY / HEALTHCARE',
    summary: 'Support the clinical, administrative and operational professionals helping healthcare teams care for people.',
    introTitle: 'Healthcare depends on people working together.', intro: 'Care reaches beyond the exam room. Clinical professionals, administrators and support teams coordinate the details that help patients and care teams move forward.',
    focus: 'Make space for people to do their best work.', photo: 'photo-1576091160399-112ba8d25d1d', photoAlt: 'Healthcare professional working in a clinical setting', secondPhoto: 'photo-1579684385127-1ef15d508118', secondAlt: 'Healthcare team discussing patient care', theme: 'health', layout: 'cinematic', visual: 'health',
    points: [['01', 'Clinical support', 'Contribute to coordinated care and patient-facing teams.'], ['02', 'Healthcare administration', 'Keep scheduling, records and communication organized.'], ['03', 'Operations', 'Support the people, services and processes behind care delivery.'], ['04', 'Patient support', 'Help create clear, compassionate experiences for patients and families.']],
    stages: ['Listen to the need', 'Support the care team', 'Help the work continue'], cta: 'Find where your skills can support care.', related: [['Non-IT Careers', '/non-it'], ['Business & Finance', '/industries/business-finance']],
  },
  engineering: {
    title: ['ENGINEER', 'WHAT THE', 'WORLD NEEDS', 'NEXT.'], eyebrow: 'INDUSTRY / ENGINEERING',
    summary: 'Connect engineering talent with work across design, systems, manufacturing, infrastructure and technical problem solving.',
    introTitle: 'Engineering turns ideas into things people use.', intro: 'Engineering careers span disciplines and environments. They share curiosity, careful analysis and a commitment to making systems work in the real world.',
    focus: 'Design with rigor. Build with purpose.', photo: 'photo-1581091226825-a6a2a5aee158', photoAlt: 'Engineer examining equipment in a modern workplace', secondPhoto: 'photo-1581092160562-40aa08e78837', secondAlt: 'Engineer working with technical equipment', theme: 'ochre', layout: 'cinematic', visual: 'engineering',
    points: [['01', 'Mechanical & electrical', 'Design, analyze and improve physical systems and equipment.'], ['02', 'Civil & infrastructure', 'Help plan and build the environments communities rely on.'], ['03', 'Manufacturing', 'Improve production systems, quality and process reliability.'], ['04', 'Technical project work', 'Coordinate engineering tasks, documentation and delivery.']],
    stages: ['Define the constraints', 'Design and validate', 'Deliver and learn'], cta: 'Bring your problem-solving to the next build.', related: [['IT Infrastructure', '/industries/it-infrastructure'], ['Non-IT Careers', '/non-it']],
  },
  'sales-marketing': {
    title: ['CONNECT', 'THE IDEA', 'TO THE', 'RIGHT PEOPLE.'], eyebrow: 'INDUSTRY / SALES & MARKETING',
    summary: 'Support the people who understand customers, tell a product story and build meaningful business relationships.',
    introTitle: 'Good growth begins by listening.', intro: 'Sales and marketing bring together research, communication, customer understanding and follow-through. The strongest work starts with people, not noise.',
    focus: 'Create relevant connections and useful conversations.', photo: 'photo-1552664730-d307ca884978', photoAlt: 'Team discussing customer and business strategy', secondPhoto: 'photo-1556761175-b413da4baf72', secondAlt: 'Colleagues planning a marketing campaign', theme: 'coral', layout: 'editorial', visual: 'campaign',
    points: [['01', 'Sales', 'Build relationships, understand needs and guide a clear next step.'], ['02', 'Marketing', 'Shape useful messages and experiences for a defined audience.'], ['03', 'Customer success', 'Help customers realize value through ongoing support.'], ['04', 'Communications', 'Share consistent, clear information across channels.']],
    stages: ['Understand the audience', 'Shape the message', 'Build the relationship'], cta: 'Put your people skills to work.', related: [['Business & Finance', '/industries/business-finance'], ['Non-IT Careers', '/non-it']],
  },
}